### ISSUE TITLE
I would like to request pull by putting the mock server function in this library. Is it possible?

### ISSUE THREAD

**Issue by uk1996** [dotX12/fastapi-gateway#9]
Hello, I am a developer who is developing a gateway using the fastapi_gateway library. But when the service to connect to the gateway was not developed, I wanted to use the gateway as a mock server. Therefore, by adding the bool type mock parameter of the route decoder, I will distinguish whether the corresponding API of the gateway is connected to the service, and if the mock is True, I will respond to the sample data added to the responses parameter. Is this effective in your opinion? If you think it's efficient, Is it okay if I develop the function and make a pull request?

**Comment by dotX12** [comment]
@uk1996, hello!
It seems to me that this is clearly not the task of the gateway, but you need to mock the answer on the final server.

**Comment by dotX12** [comment]
![image](https://user-images.githubusercontent.com/64792903/229124714-cdc2ab9b-e7e3-43ff-a2b0-4fb488736529.png)

**Comment by uk1996** [comment]
I understand, thank you for taking the time to reply!
